language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
script:
    - dotnet restore
    - dotnet build -c release
    - dotnet test MockAttributes.Demo/MockAttributes.Demo.csproj
notifications:
    email: false
